#+TITLE: UNSORTED-MERGE EXPERIMENT: DESIGN DOCUMENT

* INTRODUCTION
This document describes the design for the unsorted-merge experiment.
The requirements for thie experiment can be found in the requirements
document.


* UNSORTED-MERGE AS A CONSTRAINED SHUFFLE EXPERIMENT
The unsorted-merge experiment is a special case of the shuffle
experiment with additional constraints.  The constraints are applied
to the interactions.

** Interaction Contraints
The user can only pick an element to place in the result array from
the input array that has larger number as the first element.

For example, consider the following scenario:

#+BEGIN_EXAMPLE
Left = [50, 30, 20, 55]
Right = [22, 80, 90]
#+END_EXAMPLE

In the above case, the shuffle experiment would allow the user to pick
any element 50 or 22 to place in the result array.  But, in the
unsorted-merge experiment the user can only select the first element
from the =Left= array (50) because it is greater than 22.

In case one of the arrays is empty, the user can pick the remaining
numbers from the non-empty array one-by-one.


* INTERFACE
The interface for the unsorted-merge experiment is similar to the
shuffle experiment, because of the similarity discussed above.


* INTERACTIONS
The interactions are similar to the shuffle experiment except the fact
that depending on which array has the larger first element, one of the
=LEFT= or =RIGHT= buttons will always be disabled.  If both arrays
have equal first elements then and only then both =Left= and =Right=
can be enabled at the same time.
