#+TITLE: SHUFFLE EXPERIMENT: DESIGN DOCUMENT

* INTRODUCTION
This document describes the design for the shuffle experiment.  The
requirements for thie experiment can be found in the requirements
document.


* INTERFACE
The interface for arbitrary merge is similar to that of recursive
merge.


* INTERACTIONS
The interactions in the arbitrary merge experiment are similar to the
recursive merge experiment to some extent.  The differences are
dicussed below:

** Merge Node

- Recursive Merge :: The merge node appears to the user as soon as an
     array is split into two at the middle.  The user cannot apply the
     merge operation until the arrays that act as inputs to the merge
     node are not sorted, but the node is visible.

- Arbitrary Merge :: The user does not see the merge node
     automatically when the data node splits or is sorted.  The user
     needs to click on two sorted data nodes in order for the merge
     node to appear.  This difference lends the system the
     =aribitrary= nature.  The user has the ability to select any two
     data nodes and merge them if they are sorted.
